// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8EPrTx9N5DPGh4F9iJ7IclvIHMmb1Lso',
    appId: '1:534175741610:android:b873b13c6a5d001b3c42d3',
    messagingSenderId: '534175741610',
    projectId: 'readbox-3c692',
    storageBucket: 'readbox-3c692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJbxk732TbG3wZLO4SpS7f3tH4bNb1Dc8',
    appId: '1:541095232626:ios:b6d1872641954808502eeb',
    messagingSenderId: '541095232626',
    projectId: 'readbox-910a2',
    storageBucket: 'readbox-910a2.firebasestorage.app',
    iosClientId: '541095232626-0n5ecovgkvhvopc2jk7in06sbuf9d5rv.apps.googleusercontent.com',
    iosBundleId: 'com.hungvv.readbox',
  );
}
